### ISSUE TITLE
Cmdhelp no longer has line breaks.

### ISSUE THREAD

**Issue by CybertronicToon** [umby24/D3PP#9]
Cmdhelp no longer has line breaks. It displays the first 64 characters with no line breaks.
![screenshot_2021-10-27-14-21-25](https://user-images.githubusercontent.com/6559043/139132764-a3bb70e7-ba79-4e91-92cf-6c0de7495116.png)

**Comment by umby24** [comment]
sorry about that! should be covered now :)

https://github.com/umby24/D3PP/releases/tag/v0.0.7
